Input from user

In [1]:
import numpy as np
grid = []
print("Give empty spaces as zeros")
for _ in range(9):
    row = list(map(int, input("Row - {}: ".format(_+1)).strip().split()))
    grid.append(row)
print(np.matrix(grid))

Row - 1: 0 8 1 6 9 3 0 0 0
Row - 2: 0 3 0 0 0 5 9 0 0 
Row - 3: 2 0 0 0 0 7 5 0 0
Row - 4: 0 2 0 0 0 0 6 3 7 
Row - 5: 4 6 0 3 0 9 0 2 5
Row - 6: 1 5 3 0 0 0 0 4 0 
Row - 7: 0 0 8 2 0 0 0 0 6
Row - 8: 0 0 2 9 0 0 0 5 0 
Row - 9: 0 0 0 4 3 6 7 8 0


Logic

In [10]:
def possible(x,y,n):
    for i in range(9):
        if grid[y][i] == n:
            return False
    for i in range(9):
        if grid[i][x] == n:
            return False
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0 + i][x0 + j] == n:
                return False
    return True

def solve():
    for i in range(9):
        for j in range(9):
            if grid[i][j] == 0:
                for num in range(1,10):
                    if possible(j, i, num):
                        grid[i][j] = num
                        solve()
                        grid[i][j] = 0
                return
    print("YAY!!\n")
    print(np.matrix(grid))

Calling Solve function

In [11]:
solve()

YAY!!

[[5 8 1 6 9 3 2 7 4]
 [7 3 4 1 2 5 9 6 8]
 [2 9 6 8 4 7 5 1 3]
 [8 2 9 5 1 4 6 3 7]
 [4 6 7 3 8 9 1 2 5]
 [1 5 3 7 6 2 8 4 9]
 [3 7 8 2 5 1 4 9 6]
 [6 4 2 9 7 8 3 5 1]
 [9 1 5 4 3 6 7 8 2]]
