In [3]:
grid = [[0,0,0,7,9,0,0,3,4],
        [5,0,9,2,0,0,0,1,8],
        [0,3,0,6,0,0,0,0,0],
        [2,4,0,1,0,0,0,0,0],
        [0,0,8,0,4,0,9,0,0],
        [0,0,0,0,0,6,0,4,7],
        [0,0,0,0,0,8,0,2,0],
        [1,8,0,0,0,2,4,0,3],
        [4,7,0,0,1,3,0,0,0]]

In [ ]:
def possible(x,y,n):
    for i in range(9):
        if grid[y][i] == n:
            return False
    for i in range(9):
        if grid[i][x] == n:
            return False
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0 + i][x0 + j] == n:
                return False
    return True

def solve():
    for i in range(9):
        for j in range(9):
            if grid[i][j] == 0:
                for num in range(1,10):
                    if possible(j, i, num):
                        grid[i][j] = num
                        solve()
                        grid[i][j] = 0
                return
    print(np.matrix(grid))
    input()

In [16]:
solve()

[[8 2 1 7 9 5 6 3 4]
 [5 6 9 2 3 4 7 1 8]
 [7 3 4 6 8 1 2 9 5]
 [2 4 7 1 5 9 3 8 6]
 [6 1 8 3 4 7 9 5 2]
 [9 5 3 8 2 6 1 4 7]
 [3 9 6 4 7 8 5 2 1]
 [1 8 5 9 6 2 4 7 3]
 [4 7 2 5 1 3 8 6 9]]

